### ISSUE TITLE
[FYI] Critical low-level bug fixed in Silicon Labs EmberZNet 6.7.7 Zigbee stack

### ISSUE THREAD

**Issue by Hedda** [Elelabs/elelabs-zigbee-ezsp-utility#10]
@NilsBohr FYI, apparently, there is a very critical low-level bug fixed in Silicon Labs EmberZNet 6.7.7 stack and higher from Silabs:

https://community.openhab.org/t/zigbee-ikea-and-other-efr32mg1p-based-products-occasionally-crashing/109296/6

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1261#issuecomment-739313960

Thus I guess recommendation now is to upgrade Zigbee coordinator and devices to latest EmberZNet 6.7.x which currently is  6.7.8

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.7.8.0.pdf

This was a long-lived bug cause Silabs based products on the market to occasionally crash and no longer respond to APS frames.

**Comment by NilsBohr** [comment]
I assume it's closed with the recent 6.10.3 firmware release.
