### ISSUE TITLE
115200 hardware flow control verses 57600 software flow control Silicon Labs EmberZNet NCP EZSP firmware?

### ISSUE THREAD

**Issue by Hedda** [Elelabs/elelabs-zigbee-ezsp-utility#11]
@NilsBohr Please see discussed in https://github.com/grobasoz/zigbee-firmware/issues/5 as it relates to Elelabs firmware too.

**Comment by NilsBohr** [comment]
@Hedda 
Our products support 115200 with no flow control (you can select software flow control if needed)
