### ISSUE TITLE
Add ChangeLog.md file for Firmware

### ISSUE THREAD

**Issue by llaumgui** [Elelabs/elelabs-zigbee-ezsp-utility#12]
Hi,

is it possible to add a changelog of the firmware ?

Best regards.

**Comment by NilsBohr** [comment]
[#https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/721019cb542b273159372357a30251330e7c8d51](https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/721019cb542b273159372357a30251330e7c8d51)

Added
