### ISSUE TITLE
[SUGGESTION] Team up with "Zigbee for Domoticz" developers who is developing a zigpy based plugin for Domoticz

### ISSUE THREAD

**Issue by Hedda** [Elelabs/elelabs-zigbee-ezsp-utility#21]
@NilsBohr (Nikita Selednikov) Can I suggest that you (and @Elelabs ) try to reach out to @pipiche38 (Patrick Pichon) and his fellow developers about possible collaborating and teaming up to add compatibility for your [Elelabs Zigbee USB Adapter](https://elelabs.com/products/elelabs-usb-adapter.html) and [Elelabs Zigbee Raspberry Pi Shield](https://elelabs.com/products/elelabs-zigbee-shield.html) together with the new Zigbee for Domoticz Plugin implementation for Domoticz that they are developing using [zigpy](https://github.com/zigpy/zigpy) and the [bellows](https://github.com/zigpy/bellows) libraries to add compatibility with Zigbee Coordinators from different manufacturers?

You can read more back-story here -> https://github.com/zigpy/zigpy/discussions/865

Their new zigpy-based implementation was just merged into their "beta6" branch of their "Zigbee for Domoticz" plugin project as they have so far added support the zigpy radio library for Texas Instruments and is now thinking about also adding Silicon Labs EZSP (EmberZNet Serial Protocol) support via the [bellows](https://github.com/zigpy/bellows) radio library which is already used in by both Home Assistant's ZHA integration and Jeedom's Zigbee plugin implementations:

https://github.com/zigbeefordomoticz/Domoticz-Zigbee/tree/beta6

https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/Home.md

https://www.domoticz.com/wiki/ZigbeeForDomoticz

If Elelabs @NilsBohr could help sponsor them with hardware by donating a few of your [Elelabs Zigbee USB Adapters](https://elelabs.com/products/elelabs-usb-adapter.html) and [Elelabs Zigbee Raspberry Pi Shields](https://elelabs.com/products/elelabs-zigbee-shield.html) to @pipiche38, @badzz @SylvainPer and @jp-keros then maybe they could prioritize adding and testing [bellows](https://github.com/zigpy/bellows) radio library in order to support many different Silabs Zigbee NCP adapters via EZSP (EmberZNet Serial Protocol). Perhaps they can mention that they use Elelabs adapters as reference adapters for Silicon Labs EZSP compatibility. No strings attached of course as these are still hobby projects at their core with only a few developers volunteering on that project so far. 

Support for zigpy based radio libraries "Zigbee for Domoticz Plugin" for Domoticz is still in a very early stage, but those guys have long been developing a previous  "ZiGate Plugin for Domoticz" for Domoticz, (with [Domoticz](https://www.domoticz.com) itself also being a popular free and open-source DIY home automation software). So at least you know that these guys already have the experience, skills, and personal interest to develop good Zigbee plugins for Domoticz.

Again, as I understand it, zigpy, bellows, Domoticz, and this new "Zigbee for Domoticz Plugin" are all only spare-time hobby projects but still, I think that teaming up might give all involved projects some positive recognition in the Domoticz community and the whole home automation scene in general which might attract more developers and willing alpha/beta-testers from the community to come to help out with all these involved projects which in the long run could benefit all users wanting Zigbee in Domoticz to become more mature and working with more Zigbee hardware dongles than it is today.

**Comment by Hedda** [comment]
@pipiche38 Best might be if you yourself send an e-mail to "Nikita Selednikov" <sne@elelabs.com> (a.k.a. @NilsBohr on GitHub who is Product Manager at Elelabs) and summerize "Zigbee for Domoticz" plugin and the idea of supporting Silicon Labs EZSP adapters via bellows and zigpy libraries (plus add your fellow plugin developers to copy on that e-mail). Alternatively, send an e-mail to info@elelabs.com as per https://elelabs.com/#contacts

FYI, Elelabs currently sell Silicon Labs EFR32MG13 based Zigbee USB Adapter (ELU013) and Zigbee Raspberry Pi Shield (ELR023), however, I read that they are working on reflashed variants based on EFR32MG21 and EFR32MG24 (depends on Silabs supply chain I guess). Note that they sold Zigbee adapters for many years and have done such refreshes to newer and newer Silabs chips in the past which can be slightly confusing since they change SKU/article-ID but not the actual title of the products.

https://elelabs.com/products/elelabs-usb-adapter.html

https://elelabs.com/products/elelabs-zigbee-shield.html

PS: German electronics maker Popp & Co (acquired by Aeotec in 2018) also sell OEM version under their POPP brand in Europe:

https://www.popp.eu/zb-shield/

https://www.popp.eu/zb-stick/

https://aeotec.com/about/index.html

**Comment by pipiche38** [comment]
Thanks for @NilsBohr support. Integration is done, we are now moving to beta testers if any.

**Comment by Hedda** [comment]
@NilsBohr FYI, they announced "release 6" ("stable6") of their Domoticz plugin including support for EZSP via zigpy and bellows:

https://www.domoticz.com/forum/viewtopic.php?p=288569

https://github.com/zigbeefordomoticz/Domoticz-Zigbee

https://zigbeefordomoticz.github.io/wiki/

https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/Plugin_Version-6.md

@NilsBohr Are you by the way getting close to announcing and releasing newer hardware versions of Elelabs adapters for sale?

**Comment by NilsBohr** [comment]
@Hedda 
Thanks for update. @pipiche38 allready notified me.

Happy to hear, will try as soon as possible.

The updated hardware versions will be a "quiet" update. probably Q3 or Q4 2022 the products both Elelabs and white label (Popp) will be based on MG21 instead of MG13. Same enclosure, same everything. Same compatibility

**Comment by Hedda** [comment]
@NilsBohr Cool! Maybe consider updating your product pages with Domoticz plugin wiki URL under "COMPATIBLE SOFTWARE"?

https://elelabs.com/products/elelabs-usb-adapter.html

https://elelabs.com/products/elelabs-zigbee-shield.html

![image](https://user-images.githubusercontent.com/6320001/161927358-7b13b700-5891-4353-a8fd-5a317d086147.png)

Suggest point URL to this Domoticz wiki page for their Zigbee plugin -> https://www.domoticz.com/wiki/ZigbeeForDomoticz

PS: Off-topic; Maybe also add Jeedom under product pages "COMPATIBLE SOFTWARE" (their plugin also uses zigpy and bellows):

Jeedom Official Zigbee Plugin ->  https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/ (Note that require the purchase of their plugin from the Jeedom Market -> https://market.jeedom.com/index.php?v=d&p=market_display&id=4050 ).

**Comment by Hedda** [comment]
> The updated hardware versions will be a "quiet" update. probably Q3 or Q4 2022 the products both Elelabs and white label (Popp) will be based on MG21 instead of MG13. Same enclosure, same everything. Same compatibility

@NilsBohr Regardless if ship with same firmware as MG13 for compatibility can I suggest that you aim to contact developers of open-source home automation applications to send them MG21 samples as can be good if could be used as reference hardware:

https://www.home-assistant.io/integrations/zha -> https://github.com/zigpy/zigpy -> https://github.com/zigpy/bellows

https://www.domoticz.com/wiki/ZigbeeForDomoticz -> https://github.com/zigbeefordomoticz/Domoticz-Zigbee

https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/ -> https://github.com/jeedom

PS: Zigbee2MQTT and IoBroker both depends on zigbee-herdsman which also has experimental alpha support for Silabs EZSP v8:

https://github.com/Koenkk/zigbee-herdsman/issues/319

https://www.zigbee2mqtt.io -> https://github.com/Koenkk/zigbee2mqtt/

https://www.iobroker.net -> https://github.com/ioBroker/ioBroker.zigbee

**Comment by pipiche38** [comment]
@Hedda I think we can close that one.

**Comment by Hedda** [comment]
@pipiche38  Cool! Will close. Hope that @NilsBohr will send you guys their new EFR32MG21 based adapters when available ;)
