### ISSUE TITLE
[REQUEST] EmberZNet 6.8 (6.8 / 6.8.x / 6.8.x.x) NCP application firmware for Elelabs products

### ISSUE THREAD

**Issue by Hedda** [Elelabs/elelabs-zigbee-ezsp-utility#3]
@NilsBohr OK to request or suggest that Elelabs release an EmberZNet 6.8 NCP application firmware as an optional download?

Silicon Labs EmberZNet SDK version 6.8.x / 6.8.x.x was released this summer so it is new but not quite cutting-edge any more.

I believe that 6.8.0.1 or 6.8.0.2 or is currently the latest version of EmberZNet NCP application for Zigbee firmware?

**Update!** EmberZNet SDK 6.8.2.0 GA (General Availability) is officially available to the public since October 14, 2020.

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.8.2.0.pdf

Please note that release notes say that EmberZNet PRO stack v6.8 requires the latest Simplicity Studio 5 (SSv5) which is new.

Might be nice for developers and users to have the option to upgrade to the latest and greatest firmware available from SiLabs ;)

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.8.0.2.pdf

https://www.silabs.com/documents/public/quick-start-guides/qsg106-efr32-zigbee-pro.pdf

Major new Zigbee feature in EmberZNet 6.8 and later is support for concurrent multiple PANs (multi-PAN) on one coordinator:

https://www.silabs.com/documents/public/application-notes/an724-multi-network.pdf

There is also support for "Dynamic Multiprotocol Development with Bluetooth and Zigbee" which might not be as interesting.

https://www.silabs.com/documents/public/application-notes/an1133-dynamic-multiprotocol-bluetooth-zigbee.pdf

Keywords: Elelabs USB Shield SiLabs Ember ZNet EmberZNet 6.8 Zigbee Stack EFR32 EFR32MG EFR32MG1 EFR32MG2 EZSP API

**Comment by NilsBohr** [comment]
@Hedda 
Thanks for the proposal.
Yes, we will release a firmware update for SDK 6.8.

In terms of the dates: Most probably, the beginning of October.

**Comment by Hedda** [comment]
@NilsBohr Awesome! Great that you are willing to release almost cutting edge firmware as an option for users willing to try it out!

**Comment by Hedda** [comment]
FYI, I see that is unofficial (and untested?) EmberZNet 6.8.0.1 based firmware for Elelabs ELU013 here by the bellows / zigpy devs:

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

"Upload EmberZNet 6.8.0.1 based firmware on 23 Aug"

**Comment by abmantis** [comment]
Any news on this?

**Comment by Hedda** [comment]
> Any news on this?

No official release yet I think but can get unofficial EZSP v8 firmware releases for Elelabs ELU013 and ELR023 adapters here:

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

I know that is the version that that zigpy's bellows developers are testing (together with ZHA integration in Home Assistant).

**Comment by Hedda** [comment]
@NilsBohr Please consider adding an official Elelabs firmware image based on the new EmberZNet 6.8.2.0 (bug-fix) v8 version:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.8.2.0.pdf

As mention there looks to be unofficial releases available here:

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

**Comment by Hedda** [comment]
@NilsBohr Gut updated news on newer EmberZNet 6.8.x.x firmware (EmberZNet 6.8.2.0 or later) for any Elelabs adapters?

FYI, sprut666666 who makes DEFARO SprutStick Pro which is based on EFR32MG12 reported that he generally found that the new EmberZNet 6.8.2.0 firmware for their adapter to be significantly more stable than latest 6.7.x.x firmware in general but that they were having some issues with some devices using the ZLL (Zigbee Light Link) profile protocol, see https://github.com/zigpy/bellows/issues/242

Thus it might be a good idea to call the first release of EmberZNet 6.8.x.x firmware as "beta" until got it properly tested by users.

**Comment by Hedda** [comment]
FYI, Silicon Labs has now also released Zigbee EmberZNet 6.9.0.0 SDK as well:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.9.0.0.pdf

Note! EmberZNet 6.9.0.0 removes support for EM35x devices based devices.

**Comment by Hedda** [comment]
FYI, there are unofficial Silabs EmberZNet NCP 6.9.1.0 and 6.8.2.0 firmware images for Elelabs-ELU013 available here:

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

Try at your own risk.

**Comment by Hedda** [comment]
@NilsBohr  Please consider releasing Silabs EmberZNet 6.9.1 and/or 6.9.2 firmware for Elelabs adapters.

Zigbee EmberZNet 6.9.1.0 was released on 27th of January 2021 has been available for a while and as such been regression tested:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.9.1.0.pdf

However, Zigbee EmberZNet 6.9.2.0 was just released a week ago on 7th April of 2021 as a new bug-fix release for that release:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.9.2.0.pdf

FYI, looks like the community is just now starting to release and recommend Silicon Labs Zigbee EmberZNet 6.9.1 NCP firmware.

As per example:

Adminiuga has added NCP v6.9.1.0 FW images for Elelabs ELU013 and ELR023 (EFR32MG13 based)

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

Adminiuga also has added NCP v6.9.1.0 FW images for EByte-E180-Z120B (EFR32MG12 based)

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

tube0013 has as well added NCP v6.9.1.0 FW images for his Tube Zigbee Gateways based on EFR32MG21 and EFR32MG12:

https://github.com/tube0013/tube_gateways/tree/main/tube_zb_gw_efr32/Firmware/ZigBee%20Module/Series_2

https://github.com/tube0013/tube_gateways/tree/main/tube_zb_gw_efr32/Firmware/ZigBee%20Module/Pro

**Comment by Hedda** [comment]
@NilsBohr any plans for releasing newer Silabs EmberZNet NCP firmware that has been tested with Elelabs/Popp adapters?

https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

FYI, Zigbee EmberZNet 6.10.0.0 was just released on the 16th June of 2021 and newer EmberZNet 6.10 updates since then:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.0.0.pdf

EmberZNet 6.10.2.0 was released on the 8th of September of 2021

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.2.0.pdf

EmberZNet 6.10.1.0 was released on the 21st June of 2021

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.1.0.pdf

EmberZNet 6.10.3.0 was released on the 13th October of 2021

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.3.0.pdf

**Comment by NilsBohr** [comment]
@Hedda 
Actually the 6.10 firmware update is ready.
Will upload this week.

Plus we are very excited to add Thread support.
You will be able to change firmware to Thread and back to Zigbee using our utility

**Comment by NilsBohr** [comment]
@Hedda 
We have pushed the new version of the utility with firmware upgrade to Zigbee 6.10 and/or Thread 1.20.

**Comment by Hedda** [comment]
Awesome news! Thanks!

**Comment by Hedda** [comment]
@NilsBohr Can you please clarify in the changelog and if the new zb 6.10 firmware image is v6.10.3.0 or other 6.10.3.x release?

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/blob/master/data/EFR32MG13/ELE_MG13_zb_ncp_115200_610_211112.gbl

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/721019cb542b273159372357a30251330e7c8d51

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/31f8e9c09d612734edbe41619240162fe595ecc5

**Comment by Hedda** [comment]
@NilsBohr Can you clarify in changelog and the file-name if the new zb 6.10 firmware image is v6.10.3.0 or other 6.10.3.x release?

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/blob/master/data/EFR32MG13/ELE_MG13_zb_ncp_115200_610_211112.gbl

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/721019cb542b273159372357a30251330e7c8d51

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/31f8e9c09d612734edbe41619240162fe595ecc5

Awesome news regardless! Thanks!

**Comment by Hedda** [comment]
@NilsBohr Can you clarify in changelog and the file-name if the new zb 6.10 firmware image is v6.10.3.0 or other 6.10.x.x release?

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/blob/master/data/EFR32MG13/ELE_MG13_zb_ncp_115200_610_211112.gbl

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/721019cb542b273159372357a30251330e7c8d51

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/commit/31f8e9c09d612734edbe41619240162fe595ecc5

Awesome news regardless! Thanks!
