### ISSUE TITLE
Any chance to get EZBUSBA updated?

### ISSUE THREAD

**Issue by Tobster77** [Elelabs/elelabs-zigbee-ezsp-utility#33]
Dear all,

I am using the Elelabs EZBUSBA device (around five years old) and I experience a strange behaviour in Home Assistant (see https://community.home-assistant.io/t/randomly-switching-zigbee-plug/479839/2). 

Now I wonder if a firmware update would improve the situation. Is there a chance to see this stick covered within this project? Or would you be willing to guide me to the right firmware files (I did not find too much on the web)?

Thanks,
Tobias

**Comment by NilsBohr** [comment]
@Tobster77 
Sadly no.
Unfortunately the EZBUSBA is based on older silabs microcontroller (relevant at the time) EM3585. Silabs no longer provides SDK or software updates for that microcontroller, so we at Elelabs can't release new firmwares for it based on the latest SDK.

However, the Zigbee protocol itself didn't change much, so the adapter should work with majority products and software stacks on the market. Unless you want a specific new feature or have a specific issue you want to fix, there is no need to update to the latest software.

In case you wish to update your hardware to our current MG13 version of the USB stick, let us know at info@elelabs.com, we will provide you with a discount.
