### ISSUE TITLE
After flashing Aliexpress ZB-GW04-USB EFR32MG21 to ELU0141_MG21_zb_ncp_6103_211204.gbl, I get the "Couldn't communicate with the adapter" error...

### ISSUE THREAD

**Issue by Gweeee** [Elelabs/elelabs-zigbee-ezsp-utility#35]
```
`sudo python3 Elelabs_EzspFwUtility.py flash -f ./data/EFR32MG21/ELU0141_MG21_zb_ncp_6103_211204.gbl -p /dev/ttyUSB2`
2023/01/23 12:06:08 Elelabs_EzspFwUtility:   EZSP adapter in bootloader mode detected:
2023/01/23 12:06:08 Elelabs_EzspFwUtility:   Gecko Bootloader v1.9.2
2023/01/23 12:06:08 Elelabs_EzspFwUtility:   Allready in bootloader mode. No need to restart
2023/01/23 12:06:09 Elelabs_EzspFwUtility:   Successfully restarted into X-MODEM mode! Starting upload of the new firmware... DO NOT INTERRUPT(!)
.....
.....

2023/01/23 12:06:44 Elelabs_EzspFwUtility:   Firmware upload complete
2023/01/23 12:06:44 Elelabs_EzspFwUtility:   Rebooting NCP...
2023/01/23 12:06:59 Elelabs_EzspFwUtility:   Couldn't communicate with the adapter in Zigbee (EZSP) mode, Thread (Spinel) mode or bootloader mode
```

I can get the device consistently into bootloader mode and use `sudo python3 Elelabs_EzspFwUtility.py flash...` to load any of the four firmware options, but each seems to load and then throw the "Couldn't communicate with the adapter" error. Nothing I do allows for a probe anymore, whether in bootloader nor EZSP mode...
```
`sudo python3 Elelabs_EzspFwUtility.py probe -b 115200 -p /dev/ttyUSB2`
2023/01/23 12:13:09 Elelabs_EzspFwUtility:   Couldn't communicate with the adapter in Zigbee (EZSP) mode, Thread (Spinel) mode or bootloader mode
```

BTW..

```
`ls -l /dev/serial/by-id`
total 0
lrwxrwxrwx 1 root root 13 Jan 23 12:05 usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB2
lrwxrwxrwx 1 root root 13 Jan 23 11:04 usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1301815-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Jan 23 11:04 usb-Silicon_Labs_HubZ_Smart_Home_Controller_C1301815-if01-port0 -> ../../ttyUSB1
```

Also, my home assistant (and other containers) in docker are all down so there should not be any other service accessing /dev/ttyUSB2.

Is the device hosed? Any help is much appreciated, thanks!

**Comment by NilsBohr** [comment]
`ELU0141_MG21_zb_ncp_6103_211204.gbl` firmware is only for Elelabs products based on EFR32MG21 MCU.

The problem with other vendors of the MG21 USB sticks is the hardware pinout. They are probably using the different UART TX and RX pins for communication with the USB-UART converter.
So right now your product is just not communicating properly with the your PC/RPi.

You need to put the product into the bootloader mode and flash the firmware for your particular hardware. Typically you should ask your vendor for it.

P.S. I'll use this opportunity to promote our Elelabs Zigbee USB sticks ;)
https://elelabs.com/products/elelabs-usb-adapter.html

**Comment by Gweeee** [comment]
> `ELU0141_MG21_zb_ncp_6103_211204.gbl` firmware is only for Elelabs products based on EFR32MG21 MCU.
> 
> The problem with other vendors of the MG21 USB sticks is the hardware pinout. They are probably using the different UART TX and RX pins for communication with the USB-UART converter. So right now your product is just not communicating properly with the your PC/RPi.
> 
> You need to put the product into the bootloader mode and flash the firmware for your particular hardware. Typically you should ask your vendor for it.
> 
> P.S. I'll use this opportunity to promote our Elelabs Zigbee USB sticks ;) https://elelabs.com/products/elelabs-usb-adapter.html

Thanks, NilsBohr!  Due to your response, I was able to determine that the proper firmware for my device is located at https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP/README.md. 

Now my results to the command, `sudo python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyUSB2`
are 
```	2023/01/24 07:52:00 Elelabs_EzspFwUtility:   Generic Zigbee EZSP adapter detected:
	2023/01/24 07:52:00 Elelabs_EzspFwUtility:   Firmware: 6.10.3-41
	2023/01/24 07:52:00 Elelabs_EzspFwUtility:   EZSP v8
```

If I can't get this device working for my docker home assistant installation, I'll be ordering the Elelabs USB adapter.

Much appreciated!
