### ISSUE TITLE
Cannot use the utility to probe

### ISSUE THREAD

**Issue by bmarelja** [Elelabs/elelabs-zigbee-ezsp-utility#9]
When I launch the probe command on Windows 10 -  c:\Util\Elelabs\elelabs-zigbee-ezsp-utility-master>python3 Elelabs_EzspFwUtility.py probe -p COM6 I've got response: 

Traceback (most recent call last):
  File "c:\Util\Elelabs\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 21, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

What I am doing wrong ?

**Comment by Alloc186** [comment]
Just tried it yesterday and it Gives me these lines. (Shield on Raspberry 3, RaspOS). 
![IMG_20210114_184322](https://user-images.githubusercontent.com/37019014/104734873-2d557c80-5741-11eb-8403-c5a637ce84e2.jpg)

**Comment by jeffleary00** [comment]
Hi,
I am having similar issues as users above have noted.

**MY SETUP:**
- Raspberry Pi 4
- ELELabs Zigbee Shield for raspberry pi

**OS DETAILS:**
```
pi@raspberrypi:/etc $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
**CONFIGURATION**
According to ELElabs document [here](https://elelabs.com/wp-content/uploads/2020/07/ELR023_UG_21_HomeAssistant_Hassio_0.112.4.pdf), following config changes were made:
- Disabled Serial Console (cmdline.txt)
- Enabled UART Bluetooth overlay (config.txt)
- For Raspberry Pi 4 enter /dev/ttyS0 as Serial Port

**ERROR DURING PROBE TEST**
```
pi@raspberrypi:~/elelabs-zigbee-ezsp-utility $ python3 Elelabs_EzspFwUtility.py probe -p /dev/ttyS0
Traceback (most recent call last):
  File "Elelabs_EzspFwUtility.py", line 526, in <module>
    elelabs.probe()
  File "Elelabs_EzspFwUtility.py", line 307, in probe
    ezsp_status = ezsp.initEzspProtocol()
  File "Elelabs_EzspFwUtility.py", line 286, in initEzspProtocol
    ash_status = self.ash.sendResetFrame()
  File "Elelabs_EzspFwUtility.py", line 178, in sendResetFrame
    status, response = self.getResponse()
ValueError: too many values to unpack (expected 2)
```

Please advise, what we are doing wrong and how to correct the issue.
Thank You!

**Comment by jeffleary00** [comment]
> When I launch the probe command on Windows 10 - c:\Util\Elelabs\elelabs-zigbee-ezsp-utility-master>python3 Elelabs_EzspFwUtility.py probe -p COM6 I've got response:
> 
> Traceback (most recent call last):
> File "c:\Util\Elelabs\elelabs-zigbee-ezsp-utility-master\Elelabs_EzspFwUtility.py", line 21, in
> import serial
> ModuleNotFoundError: No module named 'serial'
> 
> What I am doing wrong ?

Hi,
It seems your "serial" python library is not installed on your system.
Try this, to load all requirements of this ELE package:
```
pi@raspberrypi:~/elelabs-zigbee-ezsp-utility $ sudo pip3 install -r ./requirements.txt
```
That should correct your problem.

**Comment by MattWestb** [comment]
On window dont  use py-serial 5.0 as its broken in windows so need using one older version or waiting for one fixed is released.

**Comment by pop13-13** [comment]
Having the same issue. Followed the instructions in the readme, still getting the error.

HARDWARE:
Raspberry Pi2 v1.2
Elelabs Zigbee Raspberry Pi Shield EZBPIS

![image](https://user-images.githubusercontent.com/59600465/109784386-efce8500-7c02-11eb-8b24-990e8be89192.png)

**Comment by NilsBohr** [comment]
Should be addressed and fixed in the current version of the script

**Comment by OptimalGrammar** [comment]
Doesn't seem like this has been addressed & fixed, I'm getting the same error as OP.

**Comment by Dabbadoeber** [comment]
#metoo windows COM5

C:\tmp\z>python3 Elelabs_EzspFwUtility.py probe -p /COM5
Traceback (most recent call last):
  File "C:\tmp\z\Elelabs_EzspFwUtility.py", line 21, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

C:\tmp\z>

and now how to proceed ??

**Comment by pop13-13** [comment]
You need to have the python module named serial installed on your system.
-------- Original message --------From: Dabbadoeber ***@***.***> Date: 25/11/2022  09:54  (GMT+01:00) To: Elelabs/elelabs-zigbee-ezsp-utility ***@***.***> Cc: pop13-13 ***@***.***>, Comment ***@***.***> Subject: Re: [Elelabs/elelabs-zigbee-ezsp-utility] Cannot use the utility to probe (#9) 
#metoo windows COM5
C:\tmp\z>python3 Elelabs_EzspFwUtility.py probe -p /COM5
Traceback (most recent call last):
File "C:\tmp\z\Elelabs_EzspFwUtility.py", line 21, in 
import serial
ModuleNotFoundError: No module named 'serial'
C:\tmp\z>
and now how to proceed ??

**Comment by Loeffelmaster** [comment]
No solution?
I have the same problem I installed the requirements and when I start it again I get:
Requirement already satisfied: pyserial==3.4 in c:\users\loefkeandreas\appdata\roaming\python\python311\site-packages (from -r ./requirements.txt (line 1)) (3.4)
Requirement already satisfied: xmodem==0.4.6 in c:\users\loefkeandreas\appdata\roaming\python\python311\site-packages (from -r ./requirements.txt (line 2)) (0.4.6)

**Comment by Razoralpha** [comment]
Same issue on my windows setup, requirements are already installed, but still "no module named 'serial'".
